### ISSUE TITLE
Create a favicon

### ISSUE THREAD

**Issue by kevando** [kevando/chewy#5]
Convert this image
http://www.wookietranslator.com/img/chew-btn.png

into a favicon using
http://www.favicon-generator.org/

and add it to all pages. It will be a bunch of images and meta tags, so please put the meta tags in a seperate template file and call that template file from the <head>

**Comment by sweeneyp74** [comment]
Just got this working! Made a favicons folder in imgs to hold all the images. I then added a favicon.html file that has all the includes. Lastly i used jinja to include that html file.

**Comment by sweeneyp74** [comment]
pushed the changes to master. Probably should have pushed to dev X_X

**Comment by kevando** [comment]
Sweet @sweeneyp74  Looks good. 

Can you also push it to the live site? And mark it somehow that you did.
